### PR TITLE
Fix exception when parsing EXIF data with LONG Orientation

### LINKED ISSUE #548: Internal server error when a TIFF image uses EXIF long values for rotation
Some TIFF images may use a long integer value instead of a short one to represent EXIF orientation metadata.
Cantaloupe does not support that and raises an error (tested on develop, 5.0.3, and 5.0.5).

Here is the resulting stack trace

```
java.lang.ClassCastException: class java.lang.Long cannot be cast to class java.lang.Integer (java.lang.Long and java.lang.Integer are in module java.base of loader 'bootstrap')
	at edu.illinois.library.cantaloupe.image.Metadata.readOrientationFromEXIF(Metadata.java:157)
	at edu.illinois.library.cantaloupe.image.Metadata.lambda$getOrientation$0(Metadata.java:138)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at edu.illinois.library.cantaloupe.image.Metadata.getOrientation(Metadata.java:138)
	at edu.illinois.library.cantaloupe.resource.iiif.v2.ImageInfoFactory.newImageInfo(ImageInfoFactory.java:85)
	at edu.illinois.library.cantaloupe.resource.iiif.v2.InformationResource.newRepresentation(InformationResource.java:125)
	at edu.illinois.library.cantaloupe.resource.iiif.v2.InformationResource.doGET(InformationResource.java:87)
	at edu.illinois.library.cantaloupe.resource.HandlerServlet.handle(HandlerServlet.java:97)
	at edu.illinois.library.cantaloupe.resource.HandlerServlet.doGet(HandlerServlet.java:35)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:791)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:550)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1434)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1349)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:516)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:556)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:135)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:773)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:905)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

I was able to find the underlying issue by looking at the trace logs, especially for EXIF parsing:

```
ark-cantaloupe   | 09:08:40.006 [qtp320304382-15] TRACE e.i.l.c.c.InfoService - Info for test.TIF: {"applicationVersion":"5.0.3","serializationVersion":4,"identifier":"test.TIF","mediaType":"image/tiff","numResolutions":1,"images":[{"width":2480,"height":3507,"tileWidth":2480,"tileHeight":3507}],"metadata":{"exif":{"fields":[{"tag":256,"dataType":4,"value":2480},{"tag":257,"dataType":4,"value":3507},{"tag":258,"dataType":3,"value":1},{"tag":259,"dataType":3,"value":4},{"tag":262,"dataType":3,"value":0},{"tag":274,"dataType":4,"value":1},{"tag":277,"dataType":3,"value":1},{"tag":278,"dataType":4,"value":3507},{"tag":282,"dataType":5,"value":[300,1]},{"tag":283,"dataType":5,"value":[300,1]},{"tag":296,"dataType":3,"value":2},{"tag":305,"dataType":2,"value":"Pixel Translations Inc., PIXTIFF Version 1.157"}]}}}
```

The orientation tag is n°**274** and uses here the [data type 4](https://github.com/cantaloupe-project/cantaloupe/blob/develop/src/main/java/edu/illinois/library/cantaloupe/image/exif/DataType.java#L34) which is `LONG`.
But the [ readOrientationFromEXIF](https://github.com/cantaloupe-project/cantaloupe/blob/develop/src/main/java/edu/illinois/library/cantaloupe/image/Metadata.java#L157) only supports short integers.

### PR DESCRIPTION
**Pull request by janhoy**
Fixes #548 

Based on PR #549 and adds tests as well as a more lenient parsing.

The test jpg image is a real image from the `/var/cache/cantaloupe/image/` folder of our Cantaloupe server. Somehow the generated thumbnail stored in the cache by Cantaloupe itself ended up with a `SLONG` datatype for `Orientation` field. But it turned out that the value itself was `Integer`, so a cast to `(long)` did not work. With this patch we accept `LONG`, `SHORT`, `SLONG` and `SSHORT` and then uses `instanceof` to do any casting to int.

I tried to shrink the size of the image from 36kb, but doing so with Apple Preview also rewrote the EXIF data with correct datatype :( 

For some reason we see this bug popping up all the time with 5.0.6, so we currently run a patched version of 5.0.5 in production.

### CODE REVIEW

**Comment by janhoy** [comment]
@jcoyne please consider this for next release

File: src/main/java/edu/illinois/library/cantaloupe/image/Metadata.java [hunk 1]
```diff
@@ -155,9 +153,27 @@ public Orientation getOrientation() {
...
+        if (field != null && value != null) {
+            switch (field.getDataType()) {
+              case LONG:
+              case SLONG:
+              case SHORT:
+              case SSHORT:
+                // According to spec the orientation must be an unsigned short (16 bit)
+                // However, we have seen exif data in the wild with LONG and SLONG types
+                // Thus to be lenient we accept either and convert to int (github issue #548)
+                if (value instanceof Long) {
```
Comment (janhoy) [inline src/main/java/edu/illinois/library/cantaloupe/image/Metadata.java]: Alternatively we could skip the `field.getDataType()` check and only do the instanceof check...

**Comment by jcoyne** [comment]
@janhoy Can you re-target this PR to `develop` and rebase it on `develop`?  Hopefully that will get the tests passing.

**Comment by janhoy** [comment]
@jcoyne I added the tree commits on top of develop branch, force-pushed and re-targeted the PR to `develop`. You need to kick the tires for the test workflow...

**Comment by jcoyne** [comment]
Thank you @janhoy

File: src/main/java/edu/illinois/library/cantaloupe/image/Metadata.java [hunk 2]
```diff
@@ -132,9 +130,27 @@ public Orientation getOrientation() {
...
+                case LONG:
+                case SLONG:
+                case SHORT:
+                case SSHORT:
+                    // According to spec the orientation must be an unsigned short (16 bit)
+                    // However, we have seen exif data in the wild with LONG and SLONG types
+                    // Thus to be lenient we accept either and convert to int (github issue #548)
+                    if (value instanceof Long) {
+                        orientation = Orientation.forEXIFOrientation(Math.toIntExact((long) value));
+                    } else if (value instanceof Integer) {
```
Comment (DiegoPino) [inline src/main/java/edu/illinois/library/cantaloupe/image/Metadata.java:148]: hi @janhoy question about the `else if`. How would be the `value instanceof Integer` if the field is already instance of Long? Is that a Java typing issue when the Value is read from EXIF? This is just me not knowing enough probably. Thanks!

Comment (janhoy) [reply src/main/java/edu/illinois/library/cantaloupe/image/Metadata.java:148]: I was also surprised by this. Looks like some bug somewhere, that the EXIF typing is long but it gets stuffed into an integer, thus causing ClassCastException. That's the kind of stuff you see in the wild even if it is not as per spec.

So we could really skip the reading of EXIF type and just check the Java type of the value, since we need to fall back to that anyway. The only value in the four switch-case clauses is to trigger the warn log msg, but it could also have been in an `else` clause after `instanceof` checks of Long and Integer fails.

Comment (jcoyne) [reply src/main/java/edu/illinois/library/cantaloupe/image/Metadata.java:148]: @janhoy it would be helpful to put those assumptions in a comment

Comment (jcoyne) [reply src/main/java/edu/illinois/library/cantaloupe/image/Metadata.java:148]: @janhoy We are quite happy with this contribution.  We'd like to get this merged for an upcoming release. Are you able to add these code comments?

Comment (janhoy) [reply src/main/java/edu/illinois/library/cantaloupe/image/Metadata.java:148]: I added three lines of java comment already about this, what execlty do you feel is unclear and could you propose additional comment text to fix it?

> // According to spec the orientation must be an unsigned short (16 bit)
// However, we have seen exif data in the wild with LONG and SLONG types
// Thus to be lenient we accept either and convert to int (github issue #548)

Comment (janhoy) [reply src/main/java/edu/illinois/library/cantaloupe/image/Metadata.java:148]: Added these two lines:
> // It could also happen that 'value' is in fact a Java Integer even if the
// exif data type is LONG or SLONG, so we need to check for that as well.

Hope this is mergeable and will be included in next release!

**Review by glenrobson — APPROVED** [review]

**Comment by glenrobson** [comment]
Thank you @janhoy for your work on this.
